autoexit on runs longer than 10 minutes

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -17,6 +17,15 @@ jobs:
           LLAMA_DEBUG_MODE: "true"
           BSC_RPC: https://rpc.ankr.com/bsc,https://bsc-dataseed4.binance.org
         run: |
+          if git diff --exit-code --quiet origin/main -- package.json package-lock.json
+          then
+            echo "..."
+          else
+            echo "------ ERROR ------ \n Please revert changes to package.json / package-lock.json" > /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/output.txt
+            node ${{ github.workspace }}/.github/workflows/commentResult.js /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/output.txt "${{ github.repository_owner }}" "${{ github.event.repository.name }}" "${{ github.event.number }}"
+            exit 1
+          fi
+
           RUN_FILES=$(
             MODIFIED=${{ steps.file_changes.outputs.files_modified}} \
             ADDED=${{ steps.file_changes.outputs.files_added}} \
